import '../src/components/atoms/Colors/colors.stories'
import '../src/components/atoms/Button/button.stories'
import '../src/components/atoms/Input/input.stories'
import '../src/components/atoms/Label/label.stories'
import '../src/components/atoms/Svg/svg.stories'
import '../src/components/atoms/Background/background.stories'
import '../src/components/atoms/Container/container.stories'